### ISSUE TITLE
KaTeX parse error

### ISSUE THREAD

**Issue by TanvirHasanAkash** [nature-of-code/noc-book-2#338]
`npm run build:pdf` throws the following error:

```
> noc2@1.0.0 build:pdf
> magicbook build

Config file detected: magicbook.json
F:\Coding\noc-book-2023-main\node_modules\tinyliquid\lib\index.js:68
      if (err) throw err;
               ^

ParseError: KaTeX parse error: Expected 'EOF', got '&' at position 10: 0.00 ≤ r &̲lt; 0.60
    at new ParseError (F:\Coding\noc-book-2023-main\node_modules\katex\dist\katex.js:100:14)
    at Parser.expect (F:\Coding\noc-book-2023-main\node_modules\katex\dist\katex.js:17494:13)
    at Parser.parse (F:\Coding\noc-book-2023-main\node_modules\katex\dist\katex.js:17555:12)
    at parseTree (F:\Coding\noc-book-2023-main\node_modules\katex\dist\katex.js:18561:21)
    at renderToDomTree (F:\Coding\noc-book-2023-main\node_modules\katex\dist\katex.js:18671:16)
    at Object.renderToString (F:\Coding\noc-book-2023-main\node_modules\katex\dist\katex.js:18632:16)
    at Element.<anonymous> (F:\Coding\noc-book-2023-main\node_modules\magicbook-katex\src\katex.js:53:36)
    at LoadedCheerio.each (F:\Coding\noc-book-2023-main\node_modules\cheerio\lib\api\traversing.js:519:26)
    at DestroyableTransform._transform (F:\Coding\noc-book-2023-main\node_modules\magicbook-katex\src\katex.js:50:72)
    at Transform._read (F:\Coding\noc-book-2023-main\node_modules\readable-stream\lib\_stream_transform.js:184:10) {
  position: 9
}

Node.js v20.3.0
```

**Comment by shiffman** [comment]
Resolved via #342!
